name: 'Prepare release'
description: 'Update manifests, changelog before the release'
inputs:
  branch:
    required: true
    description: "Release branch"
  commit_back:
    default: "false"
    description: "Commit and push version updates"
  changelog_update:
    default: "false"
    description: "Update changelog"
  changelog_path:
    default: "CHANGELOG.md"
    description: "Changelog file path"
  bump_version_yaml:
    default: "false"
    description: "Bump version in arbitrary YAML file"
  bump_version_yaml_path:
    description: |
      Path to the YAML where version should be bumped
      Required if `bump_version_yaml`
  bump_version_yaml_key:
    description: |
      Version key in the YAML file, in the [yq](https://mikefarah.gitbook.io/yq) format
      Required if `bump_version_yaml`
  # Sensitive inputs
  github_token:
    required: true
    description: "GitHub token to use"
  github_token_push:
    required: false
    description: "GitHub token to use pushing changes back, `github_token` if unset"
outputs:
  new_release_published:
    description: "New released published or to be published"
    value: ${{ steps.semantic_release.outputs.new_release_published }}
  new_release_version:
    description: "New release version"
    value: ${{ steps.semantic_release.outputs.new_release_version }}
  new_release_major_version:
    description: "New release major version"
    value: ${{ steps.semantic_release.outputs.new_release_major_version }}
  new_release_minor_version:
    description: "New release minor version"
    value: ${{ steps.semantic_release.outputs.new_release_minor_version }}
  new_release_patch_version:
    description: "New release patch version"
    value: ${{ steps.semantic_release.outputs.new_release_patch_version }}
  new_release_notes:
    description: "New release changelog"
    value: ${{ steps.semantic_release.outputs.new_release_notes }}
  new_release_channel:
    description: "New release channel"
    value: ${{ steps.semantic_release.outputs.new_release_channel }}
  last_release_version:
    description: "Last release version"
    value: ${{ steps.semantic_release.outputs.last_release_version }}
  last_release_git_tag:
    description: "Last release tag"
    value: ${{ steps.semantic_release.outputs.last_release_git_tag }}

runs:
  using: "composite"
  steps:
    - name: Semantic Release
      id: semantic_release
      uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        ci: false
        dry_run: true
        unset_gha_env: true
        branches: |
          [
            '${{ inputs.branch }}'
          ]
        extra_plugins: |
          conventional-changelog-conventionalcommits
    - name: Bump version in YAML
      if: ${{ fromJson(steps.semantic_release.outputs.new_release_published) && fromJson(inputs.bump_version_yaml) }}
      shell: bash
      run: |
        echo 'Bump version in YAML'
        sh ${{ github.action_path }}/bump_yaml.sh \
          ${{ inputs.bump_version_yaml_path }} \
          ${{ inputs.bump_version_yaml_key }} \
          ${{ steps.semantic_release.outputs.new_release_version }}
    - name: Update the changelog
      if: ${{ fromJson(steps.semantic_release.outputs.new_release_published) && fromJson(inputs.changelog_update) }}
      shell: bash
      run: |
        echo 'Update the changelog'
        if [ ! -f '${{ inputs.changelog_path }}' ]; then touch '${{ inputs.changelog_path }}'; fi
        cat <(echo '${{ steps.semantic_release.outputs.new_release_notes }}') <(echo) ${{ inputs.changelog_path }} > /tmp/chlog
        mv /tmp/chlog ${{ inputs.changelog_path }}
    - name: Commit back
      if: ${{ fromJson(steps.semantic_release.outputs.new_release_published) && fromJson(inputs.commit_back) }}
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token_push || inputs.github_token }}
      with:
        commit_message: |
          doc: Update version/changelog
