name: 'Prepare release'
description: 'Update manifests, changelog before the release'
inputs:
  pre_release:
    default: "false"
    description: Should a pre-release happen (${version}-alpha.1, ${version}-alpha.2, ...) instead of normal release
  tag_prefix:
    default: ""
    description: Tag prefix to parse/create, commonly empty, module name if monorepo, or "v"
  git_cliff_version:
    default: "2.10.1"
    description: "git-cliff version"
  include_paths:
    default: '**/*'
    description: |
      Include paths to determine related commits, comma-separated list
      Used as the --include-path values for `git-cliff` (globs supported), for example:
      include_path: 'charts/chart-one/**/*,charts/chart-two/**/*'
  exclude_paths:
    default: ''
    description: |
      Exclude paths to determine related commits, comma-separated list
      Used as the --exclude-path values for `git-cliff` (globs supported), for example:
      exclude_path: 'charts/chart-one/**/*,charts/chart-two/**/*'
  changelog_update:
    default: "false"
    description: "Update changelog"
  changelog_path:
    default: "CHANGELOG.md"
    description: "Changelog file path"
  bump_version_yaml:
    default: "false"
    description: "Bump version in arbitrary YAML file"
  bump_version_yaml_path:
    description: |
      Path to the YAML where version should be bumped
      Required if `bump_version_yaml`
  bump_version_yaml_key:
    description: |
      Version key in the YAML file, in the [yq](https://mikefarah.gitbook.io/yq) format.
      Coma-separated list of keys are supported (no spaces)
      Required if `bump_version_yaml`
outputs:
  new_release_published:
    description: "New released published or to be published"
    value: ${{ steps.semantic_release.outputs.new_release_published }}
  new_release_version:
    description: "New release version"
    value: ${{ steps.semantic_release.outputs.new_release_version }}
  new_release_git_tag:
    description: "New release git tag"
    value: ${{ steps.semantic_release.outputs.new_release_git_tag }}
  new_release_notes:
    description: "New release changelog"
    value: ${{ steps.semantic_release.outputs.new_release_notes }}
  last_release_version:
    description: "Last release version"
    value: ${{ steps.semantic_release.outputs.last_release_version }}
  last_release_git_tag:
    description: "Last release tag"
    value: ${{ steps.semantic_release.outputs.last_release_git_tag }}


runs:
  using: "composite"
  steps:
    - name: Install git-cliff
      shell: bash
      env:
        GIT_CLIFF_VERSION: ${{ inputs.git_cliff_version }}
      run: |
        wget -c -O - "https://github.com/orhun/git-cliff/releases/download/v${GIT_CLIFF_VERSION}/git-cliff-${GIT_CLIFF_VERSION}-x86_64-unknown-linux-gnu.tar.gz" \
          | tar xfvpz - --directory /usr/local/bin --strip-components=1 "git-cliff-${GIT_CLIFF_VERSION}/git-cliff"
    - name: Semantic Release attributes (git-cliff)
      id: semantic_release
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        TAG_PREFIX: ${{ inputs.tag_prefix }}
        INCLUDE_PATHS: ${{ inputs.include_paths }}
        EXCLUDE_PATHS: ${{ inputs.exclude_paths }}
      run: |
        python "${ACTION_PATH}/git_cliff.py" \
          --config "${ACTION_PATH}/cliff.toml" \
          --tag-prefix "${TAG_PREFIX}" \
          --include-paths "${INCLUDE_PATHS}" \
          --exclude-paths "${EXCLUDE_PATHS}"
    - name: Bump version in YAML
      if: ${{ fromJson(steps.semantic_release.outputs.new_release_published) && fromJson(inputs.bump_version_yaml) }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        BUMP_VERSION_YAML_PATH: ${{ inputs.bump_version_yaml_path }}
        BUMP_VERSION_YAML_KEY: ${{ inputs.bump_version_yaml_key }}
      run: |
        echo 'Bump version in YAML'
        sh "${ACTION_PATH}/bump_yaml.sh" \
          "${BUMP_VERSION_YAML_PATH}" \
          "${BUMP_VERSION_YAML_KEY}" \
          "${{ steps.semantic_release.outputs.new_release_version }}"
    - name: Update the changelog
      if: ${{ fromJson(steps.semantic_release.outputs.new_release_published) && fromJson(inputs.changelog_update) }}
      shell: bash
      env:
        CHANGELOG_PATH: ${{ inputs.changelog_path }}
      run: |
        echo 'Update the changelog'
        if [ ! -f "${CHANGELOG_PATH}" ]; then touch "${CHANGELOG_PATH}"; fi

        cat > /tmp/chlog <<- EOF
        ${{ steps.semantic_release.outputs.new_release_notes }}

        $(cat "${CHANGELOG_PATH}")
        EOF
        mv /tmp/chlog "${CHANGELOG_PATH}"
